---
- name: Install Podman and related packages on Debian/Ubuntu
  become: true
  ansible.builtin.apt:
    name: "{{ podman_extra_packages }}"
    state: present
    update_cache: true

- name: Ensure rootless user exists
  become: true
  ansible.builtin.user:
    name: "{{ podman_rootless_user }}"
    state: present
    create_home: true
    shell: /usr/sbin/nologin

- name: Enable linger for rootless user
  become: true
  ansible.builtin.command:
    cmd: loginctl enable-linger "{{ podman_rootless_user }}"
  changed_when: false

- name: Configure subuids for rootless operation
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subuid
    line: "{{ podman_rootless_user }}:100000:65536"
    create: true
    mode: "0644"
  notify: Reload systemd

- name: Configure subgids for rootless operation
  become: true
  ansible.builtin.lineinfile:
    path: /etc/subgid
    line: "{{ podman_rootless_user }}:100000:65536"
    create: true
    mode: "0644"
  notify: Reload systemd

- name: Permit rootless containers to bind to ports 80 and 443
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: 80
    state: present
    reload: true
