---
# Container
caddy_container_name: caddy
caddy_image: docker.io/library/caddy:2
caddy_restart_policy: unless-stopped

# Ports (host:container)
caddy_port_http: 80
caddy_port_https: 443

# Host paths
caddy_config_dir: "/home/{{ podman_rootless_user }}/caddy"
caddy_data_dir: "{{ caddy_config_dir }}/data"
caddy_config_file: "{{ caddy_config_dir }}/Caddyfile"

# Sites list (apps behind Caddy)
caddy_sites:
  - name: api.yoga-quote.devopshomelab.ru
    port: 3002
