---
- name: Reload user systemd
  become: true
  become_user: '{{ podman_rootless_user }}'
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart caddy service
  become: true
  become_user: '{{ podman_rootless_user }}'
  ansible.builtin.systemd:
    name: caddy.service
    scope: user
    state: restarted
